name: Publish Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  publish_job:
    name: Publish
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 20
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Publish
        env:
          GPG_SIGNING_KEY_ID: ${{ secrets.GPG_SIGNING_KEY_ID }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          GPG_SIGNING_SECRET_KEY: ${{ secrets.GPG_SIGNING_SECRET_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew publishReleasePublicationToMavenRepository
